name: fluidlab
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - ca-certificates=2022.07.19=h06a4308_0
  - certifi=2022.6.15=py37h06a4308_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - intel-openmp=2021.4.0=h06a4308_3561
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py37h7f8727e_0
  - mkl_fft=1.3.1=py37hd3c417c_0
  - mkl_random=1.2.2=py37h51133e4_0
  - ncurses=6.3=h5eee18b_3
  - numpy-base=1.21.5=py37ha15fc14_3
  - openssl=1.1.1q=h7f8727e_0
  - pip=22.1.2=py37h06a4308_0
  - pybind11=2.9.2=py37h79cecc1_0
  - python=3.7.13=h12debd9_0
  - pytorch=1.12.1=py3.7_cuda11.3_cudnn8.3.2_0
  - pytorch-mutex=1.0=cuda
  - readline=8.1.2=h7f8727e_1
  - setuptools=63.4.1=py37h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.39.2=h5082296_0
  - tk=8.6.12=h1ccaba5_0
  - torchaudio=0.12.1=py37_cu113
  - typing_extensions=4.3.0=py37h06a4308_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h7f8727e_1
  - zlib=1.2.12=h7f8727e_2
  - pip:
    - absl-py==1.2.0
    - addict==2.4.0
    - alabaster==0.7.12
    - ale-py==0.7.4
    - alembic==1.8.1
    - anyio==3.6.1
    - arch==5.3.0
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - astunparse==1.6.3
    - attrs==22.1.0
    - autopage==0.5.1
    - autorom==0.4.2
    - autorom-accept-rom-license==0.4.2
    - babel==2.10.3
    - backcall==0.2.0
    - beautifulsoup4==4.11.1
    - black==22.8.0
    - bleach==5.0.1
    - box2d-py==2.3.8
    - cachetools==5.2.0
    - chardet==5.0.0
    - charset-normalizer==2.1.1
    - click==8.1.3
    - cliff==3.10.1
    - cloudpickle==2.2.0
    - cmaes==0.8.2
    - cmd2==2.4.2
    - colorama==0.4.5
    - colorlog==6.7.0
    - commonmark==0.9.1
    - coverage==6.4.4
    - cycler==0.11.0
    - dataproperty==0.55.0
    - debugpy==1.6.3
    - decorator==5.1.1
    - defusedxml==0.7.1
    - deprecation==2.1.0
    - dill==0.3.5.1
    - docker-pycreds==0.4.0
    - docutils==0.17.1
    - entrypoints==0.4
    - evdev==1.6.0
    - execnet==1.9.0
    - fastjsonschema==2.16.1
    - filelock==3.8.0
    - flake8==3.9.2
    - flake8-bugbear==22.8.23
    - fonttools==4.37.1
    - freetype-py==2.3.0
    - future==0.18.2
    - geomloss==0.2.5
    - gitdb==4.0.9
    - gitpython==3.1.27
    - google-auth==2.11.0
    - google-auth-oauthlib==0.4.6
    - greenlet==1.1.3
    - grpcio==1.48.1
    - gym==0.21.0
    - gym-minigrid==1.0.3
    - huggingface-hub==0.8.1
    - huggingface-sb3==2.2.3
    - idna==3.3
    - imageio==2.21.2
    - imagesize==1.4.1
    - importlab==0.7
    - importlib-metadata==4.12.0
    - importlib-resources==5.9.0
    - iniconfig==1.1.1
    - ipykernel==6.15.2
    - ipython==7.34.0
    - ipython-genutils==0.2.0
    - ipywidgets==8.0.2
    - isort==5.10.1
    - jedi==0.18.1
    - jinja2==3.1.2
    - joblib==1.1.0
    - json5==0.9.10
    - jsonschema==4.15.0
    - jupyter-client==7.3.5
    - jupyter-core==4.11.1
    - jupyter-packaging==0.12.3
    - jupyter-server==1.18.1
    - jupyterlab==3.4.6
    - jupyterlab-pygments==0.2.2
    - jupyterlab-server==2.15.1
    - jupyterlab-widgets==3.0.3
    - kiwisolver==1.4.4
    - libcst==0.4.7
    - livereload==2.6.3
    - lxml==4.9.1
    - mako==1.2.2
    - markdown==3.4.1
    - markupsafe==2.1.1
    - matplotlib==3.5.3
    - matplotlib-inline==0.1.6
    - mbstrdecoder==1.1.1
    - mccabe==0.6.1
    - mesh-to-sdf==0.0.14
    - mistune==2.0.4
    - mypy-extensions==0.4.3
    - nbclassic==0.4.3
    - nbclient==0.6.7
    - nbconvert==7.0.0
    - nbformat==5.4.0
    - nest-asyncio==1.5.5
    - networkx==2.6.3
    - ninja==1.10.2.3
    - notebook==6.4.12
    - notebook-shim==0.1.0
    - numpy==1.21.6
    - oauthlib==3.2.0
    - open3d==0.15.2
    - opencv-python==4.6.0.66
    - optuna==3.0.0
    - packaging==21.3
    - panda-gym==1.1.1
    - pandas==1.3.5
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pathspec==0.10.1
    - pathtools==0.1.2
    - pathvalidate==2.5.2
    - patsy==0.5.2
    - pbr==5.10.0
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==9.2.0
    - pkgutil-resolve-name==1.3.10
    - platformdirs==2.5.2
    - plotly==5.10.0
    - pluggy==1.0.0
    - prettytable==3.4.1
    - prometheus-client==0.14.1
    - promise==2.3
    - prompt-toolkit==3.0.31
    - property-cached==1.6.4
    - protobuf==3.19.4
    - psutil==5.9.2
    - ptyprocess==0.7.0
    - py==1.11.0
    - pyaml==21.10.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pybullet==3.2.5
    - pycodestyle==2.7.0
    - pydot==1.4.2
    - pyenchant==3.2.2
    - pyflakes==2.3.1
    - pyglet==1.5.0
    - pygments==2.13.0
    - pynput==1.7.6
    - pyopengl==3.1.0
    - pyparsing==3.0.9
    - pyperclip==1.8.2
    - pyquaternion==0.9.9
    - pyrender==0.1.45
    - pyrsistent==0.18.1
    - pytablewriter==0.64.2
    - pytest==7.1.3
    - pytest-cov==3.0.0
    - pytest-env==0.6.2
    - pytest-forked==1.4.0
    - pytest-xdist==2.5.0
    - python-dateutil==2.8.2
    - python-xlib==0.31
    - pytype==2022.8.30
    - pytz==2022.2.1
    - pywavelets==1.3.0
    - pyyaml==6.0
    - pyzmq==23.2.1
    - requests==2.28.1
    - requests-oauthlib==1.3.1
    - rich==12.5.1
    - rliable==1.0.8
    - rsa==4.9
    - sb3-contrib==1.6.0
    - scikit-image==0.19.3
    - scikit-learn==1.0.2
    - scikit-optimize==0.9.0
    - scipy==1.7.3
    - seaborn==0.12.0
    - send2trash==1.8.0
    - sentry-sdk==1.9.8
    - setproctitle==1.3.2
    - shortuuid==1.0.9
    - sklearn==0.0
    - smmap==5.0.0
    - sniffio==1.3.0
    - snowballstemmer==2.2.0
    - soupsieve==2.3.2.post1
    - sourceinspect==0.0.4
    - sphinx==5.1.1
    - sphinx-autobuild==2021.3.14
    - sphinx-autodoc-typehints==1.19.2
    - sphinx-copybutton==0.5.0
    - sphinx-rtd-theme==1.0.0
    - sphinxcontrib-applehelp==1.0.2
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==2.0.0
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.5
    - sphinxcontrib-spelling==7.6.0
    - sqlalchemy==1.4.41
    - stable-baselines3==1.6.0
    - statsmodels==0.13.2
    - stevedore==3.5.0
    - tabledata==1.3.0
    - tabulate==0.8.10
    - taichi==1.1.0
    - tcolorpy==0.1.2
    - tenacity==8.0.1
    - tensorboard==2.10.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - terminado==0.15.0
    - threadpoolctl==3.1.0
    - tifffile==2021.11.2
    - tinycss2==1.1.1
    - toml==0.10.2
    - tomli==2.0.1
    - tomlkit==0.11.4
    - tornado==6.2
    - tqdm==4.64.1
    - traitlets==5.3.0
    - trimesh==3.12.9
    - typed-ast==1.5.4
    - typepy==1.3.0
    - typing-inspect==0.8.0
    - urllib3==1.26.12
    - wandb==0.13.2
    - wasabi==0.10.1
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - websocket-client==1.4.1
    - werkzeug==2.2.2
    - widgetsnbextension==4.0.3
    - yacs==0.1.8
    - zipp==3.8.1
