EXP:
  seed: 0
  env_name: 'Showcase-v0'
SOLVER:
  n_iters: 500
  init_range: 
    v: ((0.0035, 0.0, 0.0), (0.0035, 0.0, 0.0))
    p: ((0.15, 0.65, 0.5), (0.15, 0.65, 0.5))
  optim:
    # type: 'SGD'
    # lr: 0.000001
    type: 'Adam'
    lr: 5e-4
    beta_1: 0.9
    beta_2: 0.99
    bounds: (-1.0, 1.0)
