EXP:
  seed: 0
  env_name: 'IceCream-v0'
SOLVER:
  n_iters: 1000
  init_range: 
    v: ((0.0, 0.0, 0.0), (0.0, 0.0, 0.0))
    p: ((0.35, 0.3, 0.5), (0.35, 0.3, 0.5))
  optim:
    type: 'Adam'
    lr: 5e-4
    beta_1: 0.9
    beta_2: 0.99
