EXP:
  seed: 0
  env_name: 'Pouring-v0'
SOLVER:
  n_iters: 500
  init_range: 
    v: ((0.0, 0.0, 0.0, 0.0, 0.0, 0.00115), (0.0, 0.0, 0.0, 0.0, 0.0, 0.00115))
    p: ((0.6, 0.7, 0.5, 0.0, 0.0, 0.0), (0.6, 0.7, 0.5, 0.0, 0.0, 0.0))
  optim:
    type: 'Adam'
    lr: 1e-4
    beta_1: 0.9
    beta_2: 0.99
    bounds: (-1.0, 1.0)
