EXP:
  seed: 0
  env_name: 'IceCreamSimple-v0'
SOLVER:
  n_iters: 1000
  init_range: 
    v: ((0.0, 0.0005, 0.0), (0.0, 0.0005, 0.0))
    p: ((0.62, 0.36, 0.5), (0.62, 0.36, 0.5))
  optim:
    type: 'Adam'
    lr: 2e-4
    beta_1: 0.9
    beta_2: 0.99
